### ISSUE TITLE
Google Analytics order tracking code doesn't work

### ISSUE THREAD

**Issue by bluec** [yireo/Yireo_CheckoutTester#10]
Using this extension the GA/UA order tracking codes don't get inserted on the `checkouttester/index/success` page. The pageview codes still work, but specifically the order tracking codes don't.

The method responsible for inserting the order tracking code is `_getOrdersTrackingCode()` in `app/code/core/Mage/GoogleAnalytics/Block/Ga.php`

This method in turn calls either the `_getOrdersTrackingCodeUniversal()` or the `_getOrdersTrackingCodeAnalytics()` method.

These methods use `$this->getOrderIds()` to find the orders to send to GA, but using this extension this always returns NULL and the method return empty instead of returning the appropriate tracking code.

Not sure how easy this might be to fix? Would certainly be useful to be able to use this extension to debug GA order tracking.

**Comment by bluec** [comment]
Can anyone confirm this behaviour? I have been able to find more specificaly the problem:

For this to work at all the extension must first be configured to fire the event `checkout_onepage_controller_success_action` and this works as expected. The core Google Analytics module has an observer on this event which executes the `setGoogleAnalyticsOnOrderSuccessPageView()` method. 

In this method is where the problem lies:

            $block = Mage::app()->getFrontController()->getAction()->getLayout()->getBlock('google_analytics');
        if ($block) {
            $block->setOrderIds($orderIds);
        }

Here `$block` is always null so the setOrderIds is never called. I can't figure out how to fix this :(

**Comment by jissereitsma** [comment]
I can confirm that this is not working. I'm also able to confirm this is due to the event `checkout_onepage_controller_success_action`. However, this event is triggered in the code of CheckoutTester based on the simple flag for this event in the System Configuration. So can you confirm that you indeed enabled the option **Generate event**?

**Comment by bluec** [comment]
Hi Jisse, as per my second comment I can confirm that I have the config flag enabled and indeed the event is firing.

The problem is that `$block = Mage::app()->getFrontController()->getAction()->getLayout()->getBlock('google_analytics');` in the `setGoogleAnalyticsOnOrderSuccessPageView()` method always returns null. 

I am wondering now if this is because the event is being fired before the layout is loaded. In `Yireo/CheckoutTester/controllers/IndexController.php` the `successAction()` method calls `registerOrder()` which despatches the event, but this is called before `loadLayout()` maybe that is the issue?

**Comment by bluec** [comment]
Indeed changing the order fixes the problem. Shall I create a PR?

**Comment by bluec** [comment]
I have created a PR that resolve this.

**Comment by jissereitsma** [comment]
Wow, many thanks. This is really something you have to spot in the wild. I'm not building that many shops anymore so never stumbled upon this. Thanks for the PR. I will release a new version right away!

**Comment by bluec** [comment]
Glad I could be of a little help. Your extensions have helped me and many others enormously.
