### ISSUE TITLE
Access denied 2.3.2

### ISSUE THREAD

**Issue by Lewischarlton93** [yireo/Yireo_CheckoutTester#14]
Hello,

Firstly, thanks for such a great extension. I've been using this module on a number of different projects and it's all been working great.

Since upgrading to Magento 2.3.2 I've been getting an 'Access denied' issue - even when a development IP is left empty.

Do you know if there is support for this still in 2.3.2? Or is this likely to be more of an issue on my end?

Thanks!

**Comment by jissereitsma** [comment]
This was actually a bug introduced in the last version. Nobody reported this yet, but I also did not add integration test for this bug to be prevented. There is now a new release 0.0.12 that adds proper integration tests and fixes the issues described.

**Comment by jissereitsma** [comment]
Actually, this ticket was placed under the M1 version, not the M2 version of this extension. See https://github.com/yireo/Yireo_CheckoutTester2

**Comment by Lewischarlton93** [comment]
@jissereitsma  Perfect! Many thanks for your contribution 👍
